import pytest
from argparse import Namespace
from unittest.mock import patch, MagicMock
from src.cli.commands import handle_manual

@pytest.fixture
def mock_execute():
    with patch('src.cli.commands._execute_and_watch') as mock:
        yield mock

@pytest.fixture
def mock_slugify():
    with patch('src.utils.slugify.slugify') as mock:
        # Simple predictable behavior for testing: lower and replace spaces
        mock.side_effect = lambda x: x.strip().lower().replace(" ", "-")
        yield mock

@pytest.mark.parametrize("title, description, slug, tech_stack, features, expected_data", [
    # 1. Normal Case
    ("My Idea", "My Desc", "my-slug", "python, react", "login, auth",
     {
         "title": "My Idea",
         "description": "My Desc",
         "slug": "my-slug",
         "tech_stack": ["python", "react"],
         "features": ["login", "auth"]
     }),

    # 2. No Description (Fallback to Title)
    ("Simple Idea", None, None, None, None,
     {
         "title": "Simple Idea",
         "description": "Simple Idea",
         "slug": "simple-idea", # generated by mock
         "tech_stack": [],
         "features": []
     }),

    # 3. Long Title (> 100 chars)
    # Title extracted from first 50 chars.
    ("A" * 120, None, None, None, None,
     {
         "title": "A" * 50,
         "description": "A" * 120,
         "slug": "a" * 50, # generated from extracted title -> "a"*50
         "tech_stack": [],
         "features": []
     }),

    # 4. Long Title with Sentence
    # "This is the first sentence. " + "A" * 100
    # Length > 100. raw_title[:50] contains the dot.
    ("This is the first sentence. " + "A" * 100, None, None, None, None,
     {
         "title": "This is the first sentence",
         "description": "This is the first sentence. " + "A" * 100,
         "slug": "this-is-the-first-sentence",
         "tech_stack": [],
         "features": []
     }),

    # 5. Whitespace Handling
    ("  Trim Me  ", "  Desc  ", None, "  a  ,  b  ", "  x  ",
     {
         "title": "  Trim Me  ", # handle_manual does not strip title if len < 100
         "description": "  Desc  ",
         "slug": "trim-me", # mock strips before lower/replace
         "tech_stack": ["a", "b"],
         "features": ["x"]
     }),
])
def test_handle_manual_parametrized(
    mock_execute: MagicMock,
    mock_slugify: MagicMock,
    title: str,
    description: str | None,
    slug: str | None,
    tech_stack: str | None,
    features: str | None,
    expected_data: dict
) -> None:
    args = Namespace(
        command='manual',
        title=title,
        description=description,
        slug=slug,
        tech_stack=tech_stack,
        features=features,
        private=False,
        timeout=300
    )

    handle_manual(args)

    # Verify _execute_and_watch called
    mock_execute.assert_called_once()

    # Check arguments passed to _execute_and_watch
    # call_args[0] are positional args: (args, idea_data)
    passed_args = mock_execute.call_args[0][0]
    passed_data = mock_execute.call_args[0][1]

    assert passed_args == args
    assert passed_data == expected_data

    # Verify slugify called only if slug not provided
    if not slug:
        # Check that it was called with the calculated title
        mock_slugify.assert_called_with(expected_data["title"])
    else:
        mock_slugify.assert_not_called()
