# Dependabot configuration file
# This ensures dependabot bumps dependencies in pip packages
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
