"""Pydantic models for the Jules Automation Tool."""

from __future__ import annotations

from pathlib import Path

from pydantic import BaseModel, Field


def _read_scaffold_template(filename: str) -> str:
    """Read a scaffold template file, returning empty string on failure."""
    template_path = Path(__file__).parent.parent / "templates" / "scaffold" / filename
    try:
        return template_path.read_text(encoding="utf-8")
    except Exception:
        return ""


class IdeaResponse(BaseModel):
    """Represents a generated software idea."""

    title: str = Field(description="The name of the software idea.")
    description: str = Field(description="A detailed description of the idea.")
    slug: str = Field(description="A kebab-case string for GitHub repository name.")
    tech_stack: list[str] = Field(default_factory=list, description="Recommended technologies.")
    features: list[str] = Field(default_factory=list, description="Key MVP features.")


class ProjectFile(BaseModel):
    """Represents a single file in a project scaffold."""

    path: str = Field(description="Relative file path from project root.")
    content: str = Field(description="Complete file content.")
    description: str = Field(description="Brief description of the file.")


class ProjectScaffold(BaseModel):
    """Represents a complete project scaffold."""

    files: list[ProjectFile] = Field(description="List of files to create.")
    requirements: list[str] = Field(default_factory=list, description="Python dependencies.")
    run_command: str = Field(default="python main.py", description="Command to run the app.")

    @classmethod
    def create_fallback_scaffold(cls, title: str, description: str) -> "ProjectScaffold":
        """Creates a default scaffold when generation fails."""
        desc = description[:200]

        def render(filename: str) -> str:
            content = _read_scaffold_template(filename)
            # Use replace instead of format because strings like Makefile contain literal curly braces
            return content.replace("{title}", title).replace("{desc}", desc)

        return cls(
            files=[
                ProjectFile(
                    path="main.py",
                    content=render("main.py.tpl"),
                    description="Main entry point with CLI",
                ),
                ProjectFile(
                    path="src/__init__.py",
                    content=_read_scaffold_template("src_init.py.tpl"),
                    description="Package marker",
                ),
                ProjectFile(
                    path="src/core/__init__.py",
                    content=_read_scaffold_template("src_core_init.py.tpl"),
                    description="Package marker",
                ),
                ProjectFile(
                    path="src/core/app.py",
                    content=render("src_core_app.py.tpl"),
                    description="Main business logic",
                ),
                ProjectFile(
                    path="Makefile",
                    content=_read_scaffold_template("Makefile.tpl"),
                    description="Development commands",
                ),
                ProjectFile(
                    path=".env.example",
                    content=render("env.example.tpl"),
                    description="Environment template",
                ),
                ProjectFile(
                    path=".gitignore",
                    content=_read_scaffold_template("gitignore.tpl"),
                    description="Git ignore file",
                ),
                ProjectFile(
                    path="tests/__init__.py",
                    content=_read_scaffold_template("tests_init.py.tpl"),
                    description="Test package marker",
                ),
                ProjectFile(
                    path="tests/test_core.py",
                    content=render("tests_test_core.py.tpl"),
                    description="Core unit tests",
                ),
            ],
            requirements=["pytest"],
            run_command="python main.py",
        )


class FeatureItem(BaseModel):
    """A single feature map checklist item generated by Gemini."""

    priority: str = Field(description="Priority label: P0, P1, P2, or P3.")
    name: str = Field(description="Short feature name, e.g. 'JWT auth middleware'.")
    description: str = Field(description="What to build and how, referencing actual project files.")
    acceptance: list[str] = Field(default_factory=list, description="Testable acceptance criteria.")
    affected_files: list[str] = Field(default_factory=list, description="File paths affected, e.g. 'src/core/app.py'.")


class FeatureMapResponse(BaseModel):
    """Structured response for AI-generated feature maps."""

    mvp_features: list[FeatureItem] = Field(
        description="Features needed for a working prototype that can be tested and demonstrated."
    )
    production_features: list[FeatureItem] = Field(
        description="Infrastructure and hardening items needed for production deployment at scale."
    )


class WorkflowResult(BaseModel):
    """Result of the idea-to-repository workflow."""

    idea: IdeaResponse
    repo_url: str
    session_id: str | None = None
    session_url: str | None = None
    pr_url: str | None = None
